new Card("Jade", 'Gem', 2, 'AE')
new Card("SiftersPearl", 'Gem', 3, 'AE')
new Card("VriswoodAmber", 'Gem', 3, 'AE')
new Card("LeechingAgate", 'Gem', 3, 'Nameless')
new Card("DiamondCluster", 'Gem', 4, 'AE')
new Card("SearingRuby", 'Gem', 4, 'AE')
new Card("BurningOpal", 'Gem', 5, 'AE')
new Card("BanishingTopaz", 'Gem', 5, 'Depths')
new Card("CloudedSapphire", 'Gem', 6, 'AE')
new Card('BloodstoneJewel','Gem',6,'WE')
new Card('BreachOre','Gem',4,'WE')
new Card('DreadDiamond','Gem',3,'WE')
new Card('ErraticIngot','Gem',5,'WE')
new Card('FrozenMagmite','Gem',3,'WE')
new Card('ScoriaSlag','Gem',4,'WE')
new Card('VolcanicGlass','Gem',3,'WE')
new Card('AlienElement','Gem',4,'OD')
new Card('HauntedBerylite','Gem',3,'OD')
new Card('PainStone','Gem',6,'OD')
new Card('FossilizedScarab','Gem',3,'TV')
new Card("AncientCyanolith", 'Gem', 3, 'Legacy')
new Card("ArcingSilicate", 'Gem', 4, 'Legacy')
new Card("BranchingRadite", 'Gem', 4, 'Legacy')
new Card("ConductiveGrit", 'Gem', 3, 'Legacy')
new Card("CrumblingCompound", 'Gem', 5, 'Legacy')
new Card("EntangledShard", 'Gem', 4, 'Legacy')
new Card("FulmiteSlab", 'Gem', 6, 'Legacy')
new Card("GildedMarble", 'Gem', 6, 'Legacy')
new Card("JoltingCrust", 'Gem', 3, 'BS')
new Card("MentiteChunk", 'Gem', 5, 'BS')
new Card("MutedLacosite", 'Gem', 5, 'BS')
new Card("ObliviumResin", 'Gem', 5, 'BS')
new Card("PhasedPortalite", 'Gem', 4, 'Legacy')
new Card("RefinedLumenium", 'Gem', 5, 'Legacy')
new Card("ShiningTetrite", 'Gem', 6, 'BS')
new Card("SoothingTorporene", 'Gem', 3, 'Legacy')
new Card("Summonite", 'Gem', 3, 'BS')
new Card("TripliteCore", 'Gem', 4, 'BS')
new Card("VoidiumSpike", 'Gem', 3, 'BS')
new Card("PhoenixFlame", 'Spell', 3, 'AE')
new Card("SpectralEcho", 'Spell', 3, 'AE')
new Card("AmplifyVision", 'Spell', 4, 'AE')
new Card("Ignite", 'Spell', 4, 'AE')
new Card("LavaTendril", 'Spell', 4, 'AE')
new Card("VoidBond", 'Spell', 4, 'Depths')
new Card("Blaze", 'Spell', 4, 'Nameless')
new Card("DarkFire", 'Spell', 5, 'AE')
new Card("EssenceTheft", 'Spell', 5, 'AE')
new Card("FeralLightning", 'Spell', 5, 'AE')
new Card("OblivionSwell", 'Spell', 5, 'AE')
new Card("Combustion", 'Spell', 5, 'Depths')
new Card("ChaosArc", 'Spell', 6, 'AE')
new Card("PlanarInsight", 'Spell', 6, 'AE')
new Card("WildfireWhip", 'Spell', 6, 'AE')
new Card("DevouringShadow", 'Spell', 6, 'Depths')
new Card("ScryingBolt", 'Spell', 6, 'Nameless')
new Card("ArcaneNexus", 'Spell', 7, 'AE')
new Card("ConsumingVoid", 'Spell', 7, 'AE')
new Card("DisintegratingScythe", 'Spell', 7, 'Depths')
new Card("SagesBrand", 'Spell', 7, 'Nameless')
new Card("MonstrousInferno", 'Spell', 8, 'Depths')
new Card("Radiance", 'Spell', 8, 'Nameless')
new Card('Aurora','Spell',5,'WE')
new Card('Carbonize','Spell',4,'WE')
new Card('ConjureTheLost','Spell',6,'WE')
new Card('CelestialSpire','Spell',5,'WE')
new Card('ConvectionField','Spell',5,'WE')
new Card('Crystallize','Spell',8,'WE')
new Card('Equilibrium','Spell',7,'WE')
new Card('FieryTorrent','Spell',5,'WE')
new Card('JaggedLightning','Spell',4,'WE')
new Card('Kindle','Spell',4,'WE')
new Card('NovaForge','Spell',6,'WE')
new Card('PyrotechnicSurge','Spell',4,'WE')
new Card('ReduceToAsh','Spell',7,'WE')
new Card('ThoughtformFamiliar','Spell',3,'WE')
new Card('Char','Spell',8,'OD')
new Card('Catalyst','Spell',6,'OD')
new Card('FeedbackAura','Spell',5,'OD')
new Card('NetherConduit','Spell',7,'OD')
new Card('Pyromancy','Spell',7,'OD')
new Card('Scorch','Spell',5,'OD')
new Card('Resonate','Spell',6,'TV')
new Card('Conflagration','Spell',3,'TV')
new Card('Fulminate','Spell',5,'TV')
new Card('InnerFire','Spell',2,'TV')
new Card('ThermalDart','Spell',4,'TV')
new Card("ArcaneSalvo", 'Spell', 5, 'Legacy')
new Card("BendingBeam", 'Spell', 5, 'Legacy')
new Card("BladeOfWisdom", 'Spell', 6, 'BS')
new Card("BreachCollision", 'Spell', 7, 'Legacy')
new Card("BreachCommunion", 'Spell', 4, 'Legacy')
new Card("BreachFlare", 'Spell', 3, 'Legacy')
new Card("BurningCurrent", 'Spell', 3, 'BS')
new Card("DoubleTap", 'Spell', 3, 'BS')
new Card("DrainingTouch", 'Spell', 2, 'BS')
new Card("FieryConclusion", 'Spell', 5, 'Legacy')
new Card("FireChakram", 'Spell', 2, 'Legacy')
new Card("FlashOfIntellect", 'Spell', 4, 'BS')
new Card("ForceTransfusion", 'Spell', 4, 'Legacy')
new Card("GravityNode", 'Spell', 5, 'Legacy')
new Card("IncineratingFist", 'Spell', 4, 'Legacy')
new Card("NerveJab", 'Spell', 2, 'BS')
new Card("PrecisionShot", 'Spell', 3, 'BS')
new Card("PsychicEruption", 'Spell', 8, 'BS')
new Card("PyroGeist", 'Spell', 6, 'Legacy')
new Card("SparkingSiphon", 'Spell', 3, 'Legacy')
new Card("SphereOfInversion", 'Spell', 9, 'Legacy')
new Card("StarfireFrenzy", 'Spell', 6, 'Legacy')
new Card("StunningForce", 'Spell', 5, 'BS')
new Card("ThunderousOath", 'Spell', 8, 'Legacy')
new Card("WarpingHaze", 'Spell', 3, 'Legacy')
new Card("FlexingDagger", 'Relic', 2, 'AE')
new Card("BottledVortex", 'Relic', 3, 'AE')
new Card("UnstablePrism", 'Relic', 3, 'AE')
new Card("BlastingStaff", 'Relic', 4, 'AE')
new Card("FocusingOrb", 'Relic', 4, 'AE')
new Card("Transmogrifier", 'Relic', 4, 'Depths')
new Card("VimDynamo", 'Relic', 4, 'Depths')
new Card("MagesTalisman", 'Relic', 5, 'AE')
new Card("MoltenHammer", 'Relic', 5, 'Nameless')
new Card("TemporalHelix", 'Relic', 7, 'Nameless')
new Card('CairnCompass','Relic',4,'WE')
new Card('ConclaveScroll','Relic',3,'WE')
new Card('FiendCatcher','Relic',3,'WE')
new Card('MagesTotem','Relic',2,'WE')
new Card('PrimordialFetish','Relic',4,'WE')
new Card('VortexGauntlet','Relic',6,'WE')
new Card('AstralCube','Relic',5,'OD')
new Card('RiddleSphere','Relic',3,'OD')
new Card('DimensionalKey','Relic',8,'TV')
new Card('EternityCharm','Relic',3,'TV')
new Card("AdrenalBatteries", 'Relic', 7, 'Legacy')
new Card("BottledStar", 'Relic', 7, 'BS')
new Card("BraneKnife", 'Relic', 3, 'Legacy')
new Card("EtherealHand", 'Relic', 6, 'Legacy')
new Card("Geophage", 'Relic', 3, 'Legacy')
new Card("InfernalMirror", 'Relic', 5, 'Legacy')
new Card("LivingGauntlet", 'Relic', 4, 'BS')
new Card("ManifoldContainer", 'Relic', 4, 'BS')
new Card("NeuralWreath", 'Relic', 4, 'Legacy')
new Card("PropheticLens", 'Relic', 4, 'Legacy')
new Card("RealityStabilizer", 'Relic', 6, 'Legacy')
new Card("ScholarsOpus", 'Relic', 3, 'BS')
new Card("SoulCords", 'Relic', 5, 'BS')
new Card("VoidMill", 'Relic', 5, 'Legacy')
new Card("VoltaicRelay", 'Relic', 4, 'Legacy')

