new Mage("Adelheim", 'AE')
new Mage("Phaedraxa", 'AE')
new Mage("Brama", 'AE')
new Mage("Kadir", 'AE')
new Mage("Mist", 'AE')
new Mage("Jian", 'AE')
new Mage("Zhana", 'Depths')
new Mage("Nym", 'Depths')
new Mage("Reeve", 'Depths')
new Mage("Malastar", 'Nameless')
new Mage("Xaxos", 'AE')
new Mage("Lash", 'AE')
new Mage('Dezmodia','WE')
new Mage('Garu','WE')
new Mage('Gex','WE')
new Mage('Mazahaedron','WE')
new Mage('MistWE','WE')
new Mage('Quilius','WE')
new Mage('Ulgimor','WE')
new Mage('YanMagda','WE')
new Mage('Sparrow','TV')
new Mage('XaxosTV','TV')
new Mage('Indira','OD')
new Mage('Remnant','OD')
