new Boss("RageBorne", 'AE')
new Boss("CarapaceQueen", 'AE')
new Boss("CrookedMask", 'AE')
new Boss("PrinceOfGluttons", 'AE')
new Boss("HordeCrone", 'Depths')
new Boss("BlightLord", 'Nameless')
new Boss("WaywardOne", 'Nameless')
new Boss('HollowCrown','WE')
new Boss('UmbraTitan','WE')
new Boss('GateWitch','WE')
new Boss('MagusOfCloaks','WE')
new Boss('KnightOfShackles','TV')
new Boss('MaidenOfThorns','TV')
new Boss('Wraithmonger','OD')
new Boss('ThriceDeadProphet','OD')
new Boss('Bladius', 'Legacy')
new Boss('SpawningHorror', 'Legacy')
new Boss('FungalMesh', 'Legacy')
new Boss('Deathmind', 'Legacy')
new Boss('MaelstromRisen', 'Legacy')
new Boss('XaxosAscended', 'Legacy')
